--41663903R
--Francisco Javier Rodriguez Magaña
--26/01/26

CREATE TABLE MINORISTA(
    CIF VARCHAR2(9) PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    CHECK(LENGTH(CIF) = 9)
);

CREATE TABLE PRODUCTE(
    NOM VARCHAR2(50) PRIMARY KEY,
    PREU_UNITARI NUMBER NOT NULL
);

CREATE TABLE REPARTIDOR(
    NUM_SS NUMBER PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL
);

CREATE TABLE COMANDA(
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,--pk
    PREU_TOTAL NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    CIF_MINORISTA VARCHAR2(9) NOT NULL,--fk
    NOM_PRODUCTE VARCHAR2(50) NOT NULL,--fk
    QUANTITAT NUMBER NOT NULL,
    FOREIGN KEY (CIF_MINORISTA) REFERENCES MINORISTA(CIF),
    FOREIGN KEY (NOM_PRODUCTE) REFERENCES PRODUCTE(NOM)
);

CREATE TABLE INTENT_ENTREGA(
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY, --PK
    FECHA DATE NOT NULL,
    ESTAT VARCHAR2(50) NOT NULL,
    CODI_REPROGRAMAT NUMBER, --FK
    CODI_COMANDA NUMBER NOT NULL, --FK 
    NUM_SS_REPARITIDOR NUMBER NOT NULL, --FK
    FOREIGN KEY (CODI_REPROGRAMAT) REFERENCES INTENT_ENTREGA(CODI),
    FOREIGN KEY (CODI_COMANDA) REFERENCES COMANDA(CODI),
    FOREIGN KEY (NUM_SS_REPARITIDOR) REFERENCES REPARTIDOR(NUM_SS),
    UNIQUE (FECHA, CODI_COMANDA)
);

--INTRODUCIR INFORMACION

INSERT INTO MINORISTA VALUES(
    'F12345678','FRAN'
);

INSERT INTO MINORISTA VALUES(
    'G09876543','OIHER'
);

INSERT INTO PRODUCTE VALUES(
    'Teclado',30
);

INSERT INTO PRODUCTE VALUES(
    'Raton',15
);

INSERT INTO REPARTIDOR VALUES(
    123456123456,'Alex'
);

INSERT INTO COMANDA VALUES(
    
);

